-- BGT Chat database schema for Supabase (PostgreSQL)
-- Run this whole file in the Supabase SQL Editor.

-- The rooms table stores the room codes that people are allowed to join.
create table if not exists public.rooms (
    room_code text primary key,
    room_name text not null,
    created_at timestamptz not null default now()
);

-- The users_profile table stores simple display names for chat users.
-- Authentication is outside the scope of this school project, so a profile is optional.
create table if not exists public.users_profile (
    id bigint generated by default as identity primary key,
    username text not null unique,
    created_at timestamptz not null default now()
);

-- The messages table stores every chat message and links it to an existing room.
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    room_code text not null,
    username text not null,
    message_text text not null,
    created_at timestamptz not null default now(),
    constraint messages_room_code_fkey
        foreign key (room_code)
        references public.rooms (room_code)
        on update cascade
        on delete cascade,
    constraint messages_username_not_blank
        check (length(trim(username)) > 0),
    constraint messages_text_not_blank
        check (length(trim(message_text)) > 0)
);

-- This index makes loading one room's messages in time order faster.
create index if not exists messages_room_created_at_idx
    on public.messages (room_code, created_at);

-- Add the example rooms. "on conflict" makes the script safe to run again.
insert into public.rooms (room_code, room_name)
values
    ('BGT2026', 'BGT General Chat'),
    ('WEB101', 'Web Development'),
    ('CSHARP1', 'C# Programming'),
    ('DATABASE', 'Database Class')
on conflict (room_code) do update
set room_name = excluded.room_name;

-- Supabase security rules for this classroom demonstration.
-- The anon/public key may read rooms and messages and may insert messages.
alter table public.rooms enable row level security;
alter table public.users_profile enable row level security;
alter table public.messages enable row level security;

drop policy if exists "Public can read rooms" on public.rooms;
create policy "Public can read rooms"
on public.rooms for select
to anon, authenticated
using (true);

drop policy if exists "Public can read profiles" on public.users_profile;
create policy "Public can read profiles"
on public.users_profile for select
to anon, authenticated
using (true);

drop policy if exists "Public can create profiles" on public.users_profile;
create policy "Public can create profiles"
on public.users_profile for insert
to anon, authenticated
with check (length(trim(username)) > 0);

drop policy if exists "Public can read messages" on public.messages;
create policy "Public can read messages"
on public.messages for select
to anon, authenticated
using (true);

drop policy if exists "Public can send messages" on public.messages;
create policy "Public can send messages"
on public.messages for insert
to anon, authenticated
with check (
    length(trim(username)) > 0
    and length(trim(message_text)) > 0
);

grant usage on schema public to anon, authenticated;
grant select on public.rooms to anon, authenticated;
grant select, insert on public.users_profile to anon, authenticated;
grant select, insert on public.messages to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
